spring:
  application:
    name: spring-ai-functions
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

api-ninjas:
  key: ${API_NINJAS_KEY}